---
name: CI/CD
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.sh'
#  schedule:
#    - cron: '0 12 * * 0'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.sh'

jobs:
  test_and_build:
    runs-on: [ ubuntu-latest ]
    name: Code check
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3

      - name: Code formatted
        id: fmt
        run: |
          terraform fmt -check
        continue-on-error: true
