---
name: CI/CD
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.sh'
#  schedule:
#    - cron: '0 12 * * 0'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.sh'

jobs:
  test_and_build:
    runs-on: [ ubuntu-latest ]
    name: Code check
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3

      - name: Code formatted
        id: fmt
        run: |
          terraform fmt -check
      
      - name: Terraform init
        id: init
        run: |
          cd example
          terraform init -input=false
      
      - name: Terraform plan
        id: plan
        run: |
          cd example
          terraform plan -input=false
      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.52.0

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact
